add Option and Result
wrongbyte/abobrinha pull request #3
Opened 2022-12-03 17:52 UTC by wrongbyte

2022-12-05 12:36 UTC, luisholanda requested changes

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +        }
```suggestion
        match self.ask_new_todo() {
            // Não tem pq criar um Ok só para usar ? depois :)
            Some(todo) => self.show_todo(&todo),
            // Não tem nada _errado_ com oq vc escreveu, só não é comum.
            None => {
                println!("Please input a valid todo.");
                Ok(())
            },
        }
```

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +            }
Que tal usar `if let` aqui?

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +        }
Dá uma olhada no método `map_err` de `Result`, vai simplificar bastante esse código.

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +        false
Normalmente usamos `if else` nessas situações.

```suggestion
        if let Ok(input) = user_input {
            input == "y"
        } else {
            false
        }
```

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +        false
BTW, dá uma olhada no método `map_or` de `Result`.

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +        }
Mesma coisa sobre `map_err` aqui :)

2022-12-05 12:36 UTC, luisholanda commented on todo/src/main.rs
> +        }
Como você diferenciaria o caso de o usuário não ter digitado nada e um erro no stdin? Acho que o ideal aqui seria o método retornar `Result<Option<Todo>, TerminalError>`.

2022-12-05 21:51 UTC, lffg commented on todo/src/main.rs
> +                println!("Error: {:?}", error)
Atualmente, o usuário está recebendo um erro bastante 'críptico', o que acha de fazer um método no enum de erro que converte a variante para uma mensagem mais 'entendível' ao usuário final?

2022-12-05 21:51 UTC, lffg commented on todo/src/main.rs
> +    fn ask_new_todo(&mut self) -> Result<Option<Todo>, TerminalError> {
O que você acha de _também_ colocar a chamada ao método `user_intention` aqui? Aí dá para concentrar essa parte em um lugar só. Atualmente está meio separado, IMHO. O que acha?

2022-12-05 21:51 UTC, lffg commented on todo/src/main.rs
> +        }
Acho que dá para usar [`matches!`](https://doc.rust-lang.org/std/macro.matches.html) aqui, algo assim:

```suggestion
        matches!(user_input, Ok(input) if input == "y")
```

2022-12-05 21:51 UTC, lffg commented on todo/src/main.rs
> +                println!("Error: {:?}", err);
Acho que a "impressão" das mensagens de erro deve se concentrar em apenas um lugar, mais próximo à `main`. O que acha de, nesse braço do erro, simplesmente fazer o _bubble up_ para cima? Nesse caso, provavelmente daria para usar a `?`.

2022-12-07 21:26 UTC, lffg commented on todo/src/main.rs
> +    let mut stdin = Terminal::new();
Como você não está usando essa instância fora da `run`,  você pode criar ela já na `run`. Aí você também evita ter que ficar passando pelo parâmetro. :)

Btw, nitpick extremo, mas ao invés de `stdin`,  eu chamaria de `terminal`. :v

2022-12-07 21:26 UTC, lffg commented on todo/src/main.rs
>      loop {
Como você simplificaria esse `loop` em favor de um `while let`?

2022-12-07 21:26 UTC, lffg commented on todo/src/main.rs
> +            return Ok(Some(Todo::new(user_input)));
```suggestion
           Ok(Some(Todo::new(user_input)));
```

:D

2022-12-07 21:26 UTC, lffg commented on todo/src/main.rs
> +            println!("Please input a valid todo.");
Essa próxima alteração vai ser chata, mas temos vários `println!`s dentro dos métodos de `Terminal`. Como nós estamos armazenando uma instância de `Stdout` no campo `stdout`, o mais correto é utilizar o `writeln!` e passar o `self.stdout` explicitamente.

Todavia, o `writeln!(self.stdout, "...", ...)` retorna um `Result`, o que iria exigir vários `map_err` para converter o `io::Error` no `TerminalError`. Portanto, o que eu sugiro é: crie um método `writeln` que aceita uma `&str` e passa ela ao `writeln!`. Assim, você só vai precisar de um `map_err` e vai evitar os `println!`s.

2022-12-07 21:44 UTC, wrongbyte commented on todo/src/main.rs
>      loop {
nice

2022-12-08 16:56 UTC, lffg reviewed
Só mais alguns nitpicks.

2022-12-08 16:56 UTC, lffg commented on todo/src/main.rs
> +            .map_err(|error| TerminalError::Stdin(error))
```suggestion
            .map_err(TerminalError::Stdin)
```

O clippy não avisou disso?

2022-12-08 16:56 UTC, lffg commented on todo/src/main.rs
> +            .map_err(|error| TerminalError::Stdout(error))
Mesmo de cima.

2022-12-08 16:56 UTC, lffg commented on todo/src/main.rs
> +    while let Ok(Some(todo)) = terminal.ask_new_todo() {
Isso aqui vai "engolir" o `Err` retornado por `ask_new_todo`, já que nesse caso ele só vai parar a iteração. Se `ask_new_todo` tiver retornado um erro, queremos reportá-lo fazendo o bubble up para a `main`. Por isso, é importante usar a interrogação aqui.
```suggestion
    while let Some(todo) = terminal.ask_new_todo()? {
```

2022-12-08 16:56 UTC, lffg commented on todo/src/main.rs
> +        println!("{}", TerminalError::format_error(error))
```suggestion
        println!("{}", error.format_error());
```

2022-12-08 18:13 UTC, lffg approved these changes
LGTM

2022-12-08 18:20 UTC, wrongbyte commented
![image](https://user-images.githubusercontent.com/57643375/206534595-eb446999-8012-4c10-91ef-9153a32b3231.png)

2022-12-08 18:20 UTC, merged