File storage
wrongbyte/abobrinha pull request #8
Opened 2023-01-24 17:30 UTC by wrongbyte

2023-01-24 18:08 UTC, lffg requested changes

2023-01-24 18:08 UTC, lffg commented on todo/Cargo.toml
> +tokio = { version = "1", features = ["full"] }
Não é necessário _para o projeto_, mas como você está em Plataforma, eventualmente terá que lidar com isso. Então, dê uma olhada em como reduzir as _features_ do tokio _ao máximo_. I.e., utilize somente as features necessárias para compilar o seu projeto.

Ref: https://docs.rs/tokio/latest/tokio/#feature-flags

E nas docs do docs.rs, sempre há a lista completa de fflags, no menu de navegação superior:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/23662020/214370753-b6903e9e-c4f1-445f-879f-21f63fc4189f.png">

2023-01-24 18:08 UTC, lffg commented on todo/src/filestorage.rs
> +    pub path: String,
Dê uma olhada em `PathBuf` e use-o aqui.

A semântica é bem similar à diferença de `str` e `String`, i.e.:

- `PathBuf` ~ `String`
- `Path` ~ `str`

2023-01-24 18:08 UTC, lffg commented on todo/src/filestorage.rs
> +        }
Para evitar duas alocações aqui, você pode tentar fazer tudo em termos da API de Iteradores. Provavelmente terá que usar um `map` .

Talvez você também precise de usar a implementação de `collect` que, dado um iterador de `Result<T, E>`, te dê um `Result<Vec<T>, E>` (ao invés de `Vec<Result<T, E>>`). Assim, você só usa a `?` uma vez, e o `collect` retorna `Err` se o `map` encontrar qualquer `Err` ao invés de `Ok`.

[Ref.](https://doc.rust-lang.org/std/iter/trait.FromIterator.html#impl-FromIterator%3CResult%3CA%2C%20E%3E%3E-for-Result%3CV%2C%20E%3E)

2023-01-24 18:08 UTC, lffg commented on todo/src/filestorage.rs
> +                false => "[ ] - ".to_owned() + &todo.message.to_string() + "\n",
Ao invés de usar `+` para concatenar strings, use o `format!`; é um pouco mais idiomático.

2023-01-24 18:08 UTC, lffg commented on todo/src/filestorage.rs
> +        for todo in todo_list.list.iter() {
Acho que o `.iter()` aqui não é necessário.

2023-01-24 18:08 UTC, lffg commented on todo/src/filestorage.rs
> +    async fn write_filestorage(&mut self, todo_list: &mut Todos) -> Result<(), StorageError>;
Os `&mut` são necessários aqui?

2023-01-24 18:08 UTC, lffg commented on todo/src/todofile.rs
> +use tokio::fs::OpenOptions;
Acho que podemos matar este módulo.

2023-01-27 17:29 UTC, lffg reviewed
Ficou muito bom! Só alguns detalhes pequenos...

2023-01-27 17:29 UTC, lffg commented on todo/src/main.rs
> +}
Geralmente o que fazemos é criar um arquivo `repository.rs` _ao lado_ (não dentro) do diretório `repository`.

E aí o `pub mod file_storage;` vai dentro desse arquivo. Aqui fica apenas `mod repository;`.

O mesmo para o `domain` abaixo.

2023-01-27 17:29 UTC, lffg commented on todo/src/repository/file_storage.rs
> +    pub fn build_todo(line: String) -> Result<Todo, StorageError> {
Aqui você pode aceitar `&str`, o que vai evitar o `.to_string()` no caller.

2023-01-27 17:29 UTC, lffg commented on todo/src/repository/file_storage/error.rs
> +use std::{fmt};
Não esqueça de ir rodando o `cargo fmt`.

2023-01-27 17:29 UTC, lffg commented on todo/src/todocli.rs
> +        self.user_interface.show_todo_list(&todo_list.list)?;
IMHO, ao invés de passar o `&Vec` (ou o slice) para esse método, deveríamos passar o `&Todos` diretamente.

Isso é "permitido" pois o tipo `Todos` faz parte da camada de domínio.

2023-01-27 17:29 UTC, lffg commented on todo/src/todocli.rs
> +        todo_list.list.push(todo);
Idealmente o `Todos` deveria ter um método que te permite adicionar um novo TODO (por questões de encapsulamento, de modo que o vetor interno ficaria privado), mas podemos ignorar esse detalhe aqui.

2023-01-30 20:38 UTC, lffg approved these changes
LGTM. As mudanças são pequenas, então vou deixar aprovado.

2023-01-30 20:38 UTC, lffg commented on todo/src/domain/todos.rs
> +    }
É bom também implementar a trait `IntoIterator` para `Todos`. Isso é importante para garantir a "idiomacidade" da interface do seu iterável. Mas não vou bloquear o PR por isso.

2023-01-30 20:38 UTC, lffg commented on todo/src/repository/file_storage.rs
> +                false => format!("[ ] - {}\n", &todo.message.to_string()),
Aqui você _poderia_ usar a implementação de `Display` do `Todo`, mas como a forma como você salva no arquivo é uma "preocupação" do seu Storage, acho legal deixar inline mesmo.

Só tirar os `.to_string()`s.
```suggestion
                true => format!("[X] - {}\n", &todo.message),
                false => format!("[ ] - {}\n", &todo.message),
```

2023-01-30 20:38 UTC, lffg commented on todo/src/repository/file_storage.rs
> +    pub fn build_todo(line: &str) -> Result<Todo, StorageError> {
```suggestion
   fn build_todo(line: &str) -> Result<Todo, StorageError> {
```

2023-01-31 14:17 UTC, wrongbyte commented on todo/src/domain/todos.rs
> +    }
blz, vou fazer isso em outra PR

2023-01-31 14:17 UTC, merged